[package]
name = "wpascal"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "wpc"
path = "src/main.rs"

[build-dependencies]
tiny-keccak = "2.0.2"
lalrpop = "0.20.0"

[dependencies]
logos = "0.14.0"
lalrpop-util = { version = "0.20.0", default-features = false }
snailquote = "0.3.1"
bumpalo = "3.15.3"
indexmap = "2.2.3"
paste = "1.0.14"
multimap = "0.10.0"
logos-display = "0.1.2"
getopts = "0.2"

